platform :ios, '9.0'
use_frameworks!


target 'ImageLoaderDemo' do

  pod 'Alamofire'

  target 'ImageLoaderDemoTests' do
    inherit! :search_paths
  end

  target 'ImageLoaderDemoUITests' do
  end

end
